In [10]:
class Employee:#Employee class
    empCount=0 ##employeeConut (keep track of number of employee objects)
    salSum=0 #salSum (average of the salaries of the Employee object)
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayCount(self): #One of the functions in Employee class
        print ("Total Employee %d" % Employee.empCount)
    def displayEmployee(self):#another function for employee class
        print("Name : ", self.name, "Family: ", self.family , "Salary: ", self.salary, "department:",self.department)

emp1 = Employee("arya","stark",5000,"software")#Employee objects creation with intialization
emp2 = Employee("john","wick",3000,"mechanic")
print("avg:",emp2.avg())#calling average function
class FulltimeEmployee(Employee):#FulltimeEmployee class with Employee as its parent class
    def __init__(self,name,family,salary,department,c_name):#constructor for FulltimeEmployee
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setCompany(self,c_name):#one of the FulltimeEmployee class function
        self.c_name=c_name
    def getCompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
Jack=FulltimeEmployee("Jack","reacher",100000,"Front-end","Tesla")#FultimeEmployee object
Jack.setCompany("Tesla")#calling the member functions of FulltimeEmploye and Employee
Jack.getCompany(),Jack.displayEmployee(),emp1.displayCount()

avg: 4000.0
Name :  Jack Family:  reacher Salary:  100000 department: Front-end
Total Employee 3


('Tesla', None, None)

In [6]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 15, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), np.argmax(reshaped_array, axis=1)] = 0

print("Random Vector:")
print(random_vector)

print("\nReshaped Array:")
print(reshaped_array)

Random Vector:
[11.7453152   2.85775069  2.94083831  0.          9.94420342  4.01005391
  1.86007804  1.85178452  0.          5.07410577  7.56042234 12.63963176
  6.44603797  0.          4.37475607  1.4016109   0.          3.93221092
  2.98130964  1.24064749]

Reshaped Array:
[[11.7453152   2.85775069  2.94083831  0.          9.94420342]
 [ 4.01005391  1.86007804  1.85178452  0.          5.07410577]
 [ 7.56042234 12.63963176  6.44603797  0.          4.37475607]
 [ 1.4016109   0.          3.93221092  2.98130964  1.24064749]]
